### ISSUE TITLE
CT modelViewTransform

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/collision-lab#10]
```
collision-lab : build : phet
Failure to grunt snapshot-1568997272006/collision-lab:
Running "lint-all" task

/data/share/phet/continuous-testing/snapshot-1568997272006/collision-lab/js/common/view/CommonScreenView.js
  27:13  error  'modelViewTransform' is assigned a value but never used  no-unused-vars

✖ 1 problem (1 error, 0 warnings)
Fatal error: 1 Lint Errors


Approximately 9/20/2019, 10:34:32 AM
collision-lab : fuzz : require.js : load
Query: brand=phet&ea&fuzz&memoryLimit=1000
Uncaught Error: Script error for "PHETCOMMON/ModelViewTransform2", needed by: COLLISION_LAB/common/view/CommonScreenView
https://requirejs.org/docs/errors.html#scripterror
Error: Script error for "PHETCOMMON/ModelViewTransform2", needed by: COLLISION_LAB/common/view/CommonScreenView
https://requirejs.org/docs/errors.html#scripterror
    at makeError (https://bayes.colorado.edu/continuous-testing/snapshot-1568997272006/sherpa/lib/require-2.3.6.js:168:17)
    at HTMLScriptElement.onScriptError (https://bayes.colorado.edu/continuous-testing/snapshot-1568997272006/sherpa/lib/require-2.3.6.js:1738:36)
id: Bayes Chrome
Approximately 9/20/2019, 10:34:32 AM
collision-lab : fuzz : require.js : load
Query: brand=phet&ea&fuzz&memoryLimit=1000
Uncaught Error: Script error for "COLLISION_LAB/CollisionLabConstants", needed by: COLLISION_LAB/common/view/CommonScreenView
https://requirejs.org/docs/errors.html#scripterror
Error: Script error for "COLLISION_LAB/CollisionLabConstants", needed by: COLLISION_LAB/common/view/CommonScreenView
https://requirejs.org/docs/errors.html#scripterror
    at makeError (https://bayes.colorado.edu/continuous-testing/snapshot-1568997272006/sherpa/lib/require-2.3.6.js:168:17)
    at HTMLScriptElement.onScriptError (https://bayes.colorado.edu/continuous-testing/snapshot-1568997272006/sherpa/lib/require-2.3.6.js:1738:36)
id: Bayes Chrome
Approximately 9/20/2019, 10:34:32 AM
collision-lab : fuzz : require.js : run
Query: brand=phet&ea&fuzz&memoryLimit=1000
Uncaught Error: Script error for "PHETCOMMON/ModelViewTransform2", needed by: COLLISION_LAB/common/view/CommonScreenView
https://requirejs.org/docs/errors.html#scripterror
Error: Script error for "PHETCOMMON/ModelViewTransform2", needed by: COLLISION_LAB/common/view/CommonScreenView
https://requirejs.org/docs/errors.html#scripterror
    at makeError (https://bayes.colorado.edu/continuous-testing/snapshot-1568997272006/sherpa/lib/require-2.3.6.js:168:17)
    at HTMLScriptElement.onScriptError (https://bayes.colorado.edu/continuous-testing/snapshot-1568997272006/sherpa/lib/require-2.3.6.js:1738:36)
id: Bayes Chrome
Approximately 9/20/2019, 10:34:32 AM
collision-lab : fuzz : require.js : run
Query: brand=phet&ea&fuzz&memoryLimit=1000
Uncaught Error: Script error for "COLLISION_LAB/CollisionLabConstants", needed by: COLLISION_LAB/common/view/CommonScreenView
https://requirejs.org/docs/errors.html#scripterror
Error: Script error for "COLLISION_LAB/CollisionLabConstants", needed by: COLLISION_LAB/common/view/CommonScreenView
https://requirejs.org/docs/errors.html#scripterror
    at makeError (https://bayes.colorado.edu/continuous-testing/snapshot-1568997272006/sherpa/lib/require-2.3.6.js:168:17)
    at HTMLScriptElement.onScriptError (https://bayes.colorado.edu/continuous-testing/snapshot-1568997272006/sherpa/lib/require-2.3.6.js:1738:36)
id: Bayes Chrome
Approximately 9/20/2019, 10:34:32 AM
```

**Comment by KatieWoe** [comment]
In perennial:
```
Open in new tab
perennial : lint-everything
Failure to lint everything:
[4mRunning "lint-everything" task[24m

/data/share/phet/continuous-testing/snapshot-1568997272006/collision-lab/js/common/view/CommonScreenView.js
  27:13  error  'modelViewTransform' is assigned a value but never used  no-unused-vars

✖ 1 problem (1 error, 0 warnings)
Fatal error: 1 Lint Errors


Approximately 9/20/2019, 10:34:32 AM
```

**Comment by veillette** [comment]
@zepumph took care of the lint error. Closing
