### ISSUE TITLE
CT invalid position

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/collision-lab#113]
```
collision-lab : fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1593515345795/collision-lab/collision-lab_en.html?continuousTest=%7B%22test%22%3A%5B%22collision-lab%22%2C%22fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1593515345795%22%2C%22timestamp%22%3A1593518117399%7D&brand=phet&ea&fuzz&memoryLimit=1000
Query: brand=phet&ea&fuzz&memoryLimit=1000
Uncaught Error: Assertion failed: invalid position: Property#2837{Vector2(-0.7000000000000001, -0.5)}
Error: Assertion failed: invalid position: Property#2837{Vector2(-0.7000000000000001, -0.5)}
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1593515345795/assert/js/assert.js:22:13)
at CollisionLabPath.updatePath (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1593515345795/collision-lab/js/common/model/CollisionLabPath.js:117:15)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1593515345795/collision-lab/js/common/model/CollisionLabPath.js:69:42
at TinyEmitter.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1593515345795/axon/js/TinyEmitter.js:69:53)
at DerivedProperty._notifyListeners (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1593515345795/axon/js/Property.js:273:25)
at DerivedProperty.set (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1593515345795/axon/js/Property.js:171:14)
at listener (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1593515345795/axon/js/DerivedProperty.js:73:19)
at TinyEmitter.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1593515345795/axon/js/TinyEmitter.js:69:53)
at NumberProperty._notifyListeners (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1593515345795/axon/js/Property.js:273:25)
at NumberProperty.set (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1593515345795/axon/js/Property.js:171:14)
id: Bayes Chrome
Snapshot from 6/30/2020, 5:09:05 AM

----------------------------------

collision-lab : xss-fuzz
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1593515345795/collision-lab/collision-lab_en.html?continuousTest=%7B%22test%22%3A%5B%22collision-lab%22%2C%22xss-fuzz%22%5D%2C%22snapshotName%22%3A%22snapshot-1593515345795%22%2C%22timestamp%22%3A1593519852784%7D&brand=phet&ea&fuzz&stringTest=xss&memoryLimit=1000
Query: brand=phet&ea&fuzz&stringTest=xss&memoryLimit=1000
Uncaught Error: Assertion failed: invalid position: Property#2785{Vector2(-0.4986699999999999, 0.148419)}
Error: Assertion failed: invalid position: Property#2785{Vector2(-0.4986699999999999, 0.148419)}
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1593515345795/assert/js/assert.js:22:13)
at CollisionLabPath.updatePath (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1593515345795/collision-lab/js/common/model/CollisionLabPath.js:117:15)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1593515345795/collision-lab/js/common/model/CollisionLabPath.js:69:42
at TinyEmitter.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1593515345795/axon/js/TinyEmitter.js:69:53)
at DerivedProperty._notifyListeners (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1593515345795/axon/js/Property.js:273:25)
at DerivedProperty.set (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1593515345795/axon/js/Property.js:171:14)
at listener (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1593515345795/axon/js/DerivedProperty.js:73:19)
at TinyEmitter.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1593515345795/axon/js/TinyEmitter.js:69:53)
at NumberProperty._notifyListeners (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1593515345795/axon/js/Property.js:273:25)
at NumberProperty.set (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1593515345795/axon/js/Property.js:171:14)
id: Bayes Chrome
Snapshot from 6/30/2020, 5:09:05 AM
```

**Comment by brandonLi8** [comment]
Thanks @KatieWoe.

Fixed in the commit above (just a typo). Closing.
