### ISSUE TITLE
CT: no such file

### ISSUE THREAD

**Issue by veillette** [phetsims/collision-lab#12]
```
collision-lab : build : phet
Failure to grunt snapshot-1569243822356/collision-lab:
Running "lint-all" task

Running "report-media" task

Running "clean" task

Running "build" task
Building runnable repository (collision-lab, brands: phet)
Building brand: phet
Fatal error: Perennial task failed:
Error: Error: Error: ENOENT: no such file or directory, open '/data/share/phet/continuous-testing/snapshot-1569243822356/collision-lab/js/Common/Model/Ball.js'
In module tree:
    collision-lab-main
      COLLISION_LAB/collision-lab/CollisionLabScreen
        COLLISION_LAB/collision-lab/model/CollisionLabModel
          COLLISION_LAB/common/model/CommonModel

  at /data/share/phet/continuous-testing/snapshot-1569243822356/chipper/js/grunt/requireBuild.js:111:15
  at /data/share/phet/continuous-testing/snapshot-1569243822356/chipper/node_modules/requirejs/bin/r.js:3059:39
  at /data/share/phet/continuous-testing/snapshot-1569243822356/chipper/node_modules/requirejs/bin/r.js:2999:25
  at Function.prim.nextTick (/data/share/phet/continuous-testing/snapshot-1569243822356/chipper/node_modules/requirejs/bin/r.js:28083:9)
  at Object.errback (/data/share/phet/continuous-testing/snapshot-1569243822356/chipper/node_modules/requirejs/bin/r.js:2998:26)
  at Object.callback (/data/share/phet/continuous-testing/snapshot-1569243822356/chipper/node_modules/requirejs/bin/r.js:2984:23)
  at Object.then (/data/share/phet/continuous-testing/snapshot-1569243822356/chipper/node_modules/requirejs/bin/r.js:3038:23)
  at runBuild (/data/share/phet/continuous-testing/snapshot-1569243822356/chipper/node_modules/requirejs/bin/r.js:30302:48)
  at Object.execCb (/data/share/phet/continuous-testing/snapshot-1569243822356/chipper/node_modules/requirejs/bin/r.js:1946:33)
  at Module.check (/data/share/phet/continuous-testing/snapshot-1569243822356/chipper/node_modules/requirejs/bin/r.js:1133:51)
  at Module.<anonymous> (/data/share/phet/continuous-testing/snapshot-1569243822356/chipper/node_modules/requirejs/bin/r.js:1389:34)
  at /data/share/phet/continuous-testing/snapshot-1569243822356/chipper/node_modules/requirejs/bin/r.js:384:23
  at /data/share/phet/continuous-testing/snapshot-1569243822356/chipper/node_modules/requirejs/bin/r.js:1439:21
  at each (/data/share/phet/continuous-testing/snapshot-1569243822356/chipper/node_modules/requirejs/bin/r.js:309:31)
  at Module.emit (/data/share/phet/continuous-testing/snapshot-1569243822356/chipper/node_modules/requirejs/bin/r.js:1438:17)
  at Module.check (/data/share/phet/continuous-testing/snapshot-1569243822356/chipper/node_modules/requirejs/bin/r.js:1188:30)
  at Module.enable (/data/share/phet/continuous-testing/snapshot-1569243822356/chipper/node_modules/requirejs/bin/r.js:1426:22)
  at Module.init (/data/share/phet/continuous-testing/snapshot-1569243822356/chipper/node_modules/requirejs/bin/r.js:1038:26)
  at Module.<anonymous> (/data/share/phet/continuous-testing/snapshot-1569243822356/chipper/node_modules/requirejs/bin/r.js:1264:30)
  at /data/share/phet/continuous-testing/snapshot-1569243822356/chipper/node_modules/requirejs/bin/r.js:384:23
  at /data/share/phet/continuous-testing/snapshot-1569243822356/chipper/node_modules/requirejs/bin/r.js:2697:17
  at Object.execCb (/data/share/phet/continuous-testing/snapshot-1569243822356/chipper/node_modules/requirejs/bin/r.js:1946:33)
  at Module.check (/data/share/phet/continuous-testing/snapshot-1569243822356/chipper/node_modules/requirejs/bin/r.js:1133:51)
  at Module.enable (/data/share/phet/continuous-testing/snapshot-1569243822356/chipper/node_modules/requirejs/bin/r.js:1426:22)
  at Module.init (/data/share/phet/continuous-testing/snapshot-1569243822356/chipper/node_modules/requirejs/bin/r.js:1038:26)
  at /data/share/phet/continuous-testing/snapshot-1569243822356/chipper/node_modules/requirejs/bin/r.js:1710:36
  at _combinedTickCallback (internal/process/next_tick.js:132:7)
  at process._tickCallback (internal/process/next_tick.js:181:9)

Full Error details:
{}


Approximately 9/23/2019, 9:03:42 AM
```

**Comment by veillette** [comment]
This should address the issue. Let's wait for CR before closing.

**Comment by brandonLi8** [comment]
This is fixed via CT. Closing
