### ISSUE TITLE
CT name is required

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/collision-lab#17]
```
collision-lab : fuzz : require.js : load
Query: brand=phet&ea&fuzz&memoryLimit=1000
Uncaught Error: Assertion failed: name is required for screen 1
Error: Assertion failed: name is required for screen 1
    at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/snapshot-1569319623793/assert/js/assert.js:22:13)
    at https://bayes.colorado.edu/continuous-testing/snapshot-1569319623793/joist/js/HomeScreenView.js?:80:17
    at l (https://bayes.colorado.edu/continuous-testing/snapshot-1569319623793/sherpa/lib/lodash-4.17.4.min.js?:6:445)
    at Function.uu [as map] (https://bayes.colorado.edu/continuous-testing/snapshot-1569319623793/sherpa/lib/lodash-4.17.4.min.js?:67:750)
    at new HomeScreenView (https://bayes.colorado.edu/continuous-testing/snapshot-1569319623793/joist/js/HomeScreenView.js?:78:30)
    at HomeScreen.createView (https://bayes.colorado.edu/continuous-testing/snapshot-1569319623793/joist/js/HomeScreen.js?:43:16)
    at HomeScreen.initializeView (https://bayes.colorado.edu/continuous-testing/snapshot-1569319623793/joist/js/Screen.js?:260:25)
    at HomeScreen.initializeModelAndView (https://bayes.colorado.edu/continuous-testing/snapshot-1569319623793/joist/js/Screen.js?:307:12)
    at new Sim (https://bayes.colorado.edu/continuous-testing/snapshot-1569319623793/joist/js/Sim.js?:593:23)
    at https://bayes.colorado.edu/continuous-testing/snapshot-1569319623793/collision-lab/js/collision-lab-main.js?:37:17
id: Bayes Chrome
Approximately 9/24/2019, 4:07:03 AM
collision-lab : fuzz : require.js : run
Query: brand=phet&ea&fuzz&memoryLimit=1000
Uncaught Error: Assertion failed: name is required for screen 1
Error: Assertion failed: name is required for screen 1
    at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/snapshot-1569319623793/assert/js/assert.js:22:13)
    at https://bayes.colorado.edu/continuous-testing/snapshot-1569319623793/joist/js/HomeScreenView.js?:80:17
    at l (https://bayes.colorado.edu/continuous-testing/snapshot-1569319623793/sherpa/lib/lodash-4.17.4.min.js?:6:445)
    at Function.uu [as map] (https://bayes.colorado.edu/continuous-testing/snapshot-1569319623793/sherpa/lib/lodash-4.17.4.min.js?:67:750)
    at new HomeScreenView (https://bayes.colorado.edu/continuous-testing/snapshot-1569319623793/joist/js/HomeScreenView.js?:78:30)
    at HomeScreen.createView (https://bayes.colorado.edu/continuous-testing/snapshot-1569319623793/joist/js/HomeScreen.js?:43:16)
    at HomeScreen.initializeView (https://bayes.colorado.edu/continuous-testing/snapshot-1569319623793/joist/js/Screen.js?:260:25)
    at HomeScreen.initializeModelAndView (https://bayes.colorado.edu/continuous-testing/snapshot-1569319623793/joist/js/Screen.js?:307:12)
    at new Sim (https://bayes.colorado.edu/continuous-testing/snapshot-1569319623793/joist/js/Sim.js?:593:23)
    at https://bayes.colorado.edu/continuous-testing/snapshot-1569319623793/collision-lab/js/collision-lab-main.js?:37:17
id: Bayes Chrome
Approximately 9/24/2019, 4:07:03 AM
collision-lab : xss-fuzz : load
Query: brand=phet&ea&fuzz&stringTest=xss&memoryLimit=1000
Uncaught Error: Assertion failed: name is required for screen 1
Error: Assertion failed: name is required for screen 1
    at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/snapshot-1569319623793/assert/js/assert.js:22:13)
    at https://bayes.colorado.edu/continuous-testing/snapshot-1569319623793/joist/js/HomeScreenView.js?:80:17
    at l (https://bayes.colorado.edu/continuous-testing/snapshot-1569319623793/sherpa/lib/lodash-4.17.4.min.js?:6:445)
    at Function.uu [as map] (https://bayes.colorado.edu/continuous-testing/snapshot-1569319623793/sherpa/lib/lodash-4.17.4.min.js?:67:750)
    at new HomeScreenView (https://bayes.colorado.edu/continuous-testing/snapshot-1569319623793/joist/js/HomeScreenView.js?:78:30)
    at HomeScreen.createView (https://bayes.colorado.edu/continuous-testing/snapshot-1569319623793/joist/js/HomeScreen.js?:43:16)
    at HomeScreen.initializeView (https://bayes.colorado.edu/continuous-testing/snapshot-1569319623793/joist/js/Screen.js?:260:25)
    at HomeScreen.initializeModelAndView (https://bayes.colorado.edu/continuous-testing/snapshot-1569319623793/joist/js/Screen.js?:307:12)
    at new Sim (https://bayes.colorado.edu/continuous-testing/snapshot-1569319623793/joist/js/Sim.js?:593:23)
    at https://bayes.colorado.edu/continuous-testing/snapshot-1569319623793/collision-lab/js/collision-lab-main.js?:37:17
id: Bayes Chrome
Approximately 9/24/2019, 4:07:03 AM
collision-lab : xss-fuzz : run
Query: brand=phet&ea&fuzz&stringTest=xss&memoryLimit=1000
Uncaught Error: Assertion failed: name is required for screen 1
Error: Assertion failed: name is required for screen 1
    at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/snapshot-1569319623793/assert/js/assert.js:22:13)
    at https://bayes.colorado.edu/continuous-testing/snapshot-1569319623793/joist/js/HomeScreenView.js?:80:17
    at l (https://bayes.colorado.edu/continuous-testing/snapshot-1569319623793/sherpa/lib/lodash-4.17.4.min.js?:6:445)
    at Function.uu [as map] (https://bayes.colorado.edu/continuous-testing/snapshot-1569319623793/sherpa/lib/lodash-4.17.4.min.js?:67:750)
    at new HomeScreenView (https://bayes.colorado.edu/continuous-testing/snapshot-1569319623793/joist/js/HomeScreenView.js?:78:30)
    at HomeScreen.createView (https://bayes.colorado.edu/continuous-testing/snapshot-1569319623793/joist/js/HomeScreen.js?:43:16)
    at HomeScreen.initializeView (https://bayes.colorado.edu/continuous-testing/snapshot-1569319623793/joist/js/Screen.js?:260:25)
    at HomeScreen.initializeModelAndView (https://bayes.colorado.edu/continuous-testing/snapshot-1569319623793/joist/js/Screen.js?:307:12)
    at new Sim (https://bayes.colorado.edu/continuous-testing/snapshot-1569319623793/joist/js/Sim.js?:593:23)
    at https://bayes.colorado.edu/continuous-testing/snapshot-1569319623793/collision-lab/js/collision-lab-main.js?:37:17
id: Bayes Chrome
Approximately 9/24/2019, 4:07:03 AM
```

**Comment by veillette** [comment]
CT is not complaining anymore. Closing
