### ISSUE TITLE
CT invalid ball object Object

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/collision-lab#207]
```
collision-lab : multitouch-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1613972931951/collision-lab/collision-lab_en.html?continuousTest=%7B%22test%22%3A%5B%22collision-lab%22%2C%22multitouch-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1613972931951%22%2C%22timestamp%22%3A1613999466157%7D&brand=phet&ea&fuzz&fuzzPointers=2&memoryLimit=1000&supportsPanAndZoom=false
Query: brand=phet&ea&fuzz&fuzzPointers=2&memoryLimit=1000&supportsPanAndZoom=false
Uncaught Error: Assertion failed: invalid ball: [object Object]
Error: Assertion failed: invalid ball: [object Object]
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1613972931951/assert/js/assert.js:25:13)
at Explore2DBallSystem.bumpBallAwayFromOthers (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1613972931951/collision-lab/js/common/model/BallSystem.js:319:15)
at DragListener.end [as _end] (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1613972931951/collision-lab/js/common/view/BallNode.js:235:20)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1613972931951/scenery/js/listeners/DragListener.js:337:25
at DragListener.onRelease (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1613972931951/scenery/js/listeners/PressListener.js:646:17)
at Action.execute (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1613972931951/axon/js/Action.js:225:18)
at DragListener.release (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1613972931951/scenery/js/listeners/PressListener.js:427:25)
at DragListener.release (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1613972931951/scenery/js/listeners/DragListener.js:333:11)
at DragListener.pointerUp (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1613972931951/scenery/js/listeners/PressListener.js:757:12)
at Input.dispatchToListeners (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1613972931951/scenery/js/input/Input.js:1842:25)
id: Bayes Chrome
Snapshot from 2/21/2021, 10:48:51 PM
```

**Comment by KatieWoe** [comment]
```
collision-lab : pan-and-zoom-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1648757578076/collision-lab/collision-lab_en.html?continuousTest=%7B%22test%22%3A%5B%22collision-lab%22%2C%22pan-and-zoom-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1648757578076%22%2C%22timestamp%22%3A1648764089204%7D&brand=phet&ea&fuzz&fuzzPointers=2&memoryLimit=1000&supportsPanAndZoom=true
Query: brand=phet&ea&fuzz&fuzzPointers=2&memoryLimit=1000&supportsPanAndZoom=true
Uncaught Error: Assertion failed: invalid ball: [object Object]
Error: Assertion failed: invalid ball: [object Object]
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1648757578076/assert/js/assert.js:25:13)
at Explore2DBallSystem.bumpBallAwayFromOthers (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1648757578076/chipper/dist/js/collision-lab/js/common/model/BallSystem.js:282:15)
at Object.BallMassSlider.options.endDrag (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1648757578076/chipper/dist/js/collision-lab/js/common/view/BallMassSlider.js:47:18)
at DragListener.end [as _end] (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1648757578076/chipper/dist/js/sun/js/Slider.js:275:19)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1648757578076/chipper/dist/js/scenery/js/listeners/DragListener.js:248:25
at DragListener.onRelease (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1648757578076/chipper/dist/js/scenery/js/listeners/PressListener.js:575:17)
at PhetioAction.execute (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1648757578076/chipper/dist/js/tandem/js/PhetioAction.js:91:17)
at DragListener.release (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1648757578076/chipper/dist/js/scenery/js/listeners/PressListener.js:333:25)
at DragListener.release (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1648757578076/chipper/dist/js/scenery/js/listeners/DragListener.js:245:11)
at DragListener.pointerUp (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1648757578076/chipper/dist/js/scenery/js/listeners/PressListener.js:668:12)
id: Bayes Chrome
Snapshot from 3/31/2022, 2:12:58 PM
```

**Comment by jonathanolson** [comment]
Doesn't seem to be happening anymore!
