### ISSUE TITLE
Error: Assertion failed: Corner overlap on left edge

### ISSUE THREAD

**Issue by samreid** [phetsims/collision-lab#217]
```
collision-lab : xss-fuzz
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1661601756989/collision-lab/collision-lab_en.html?continuousTest=%7B%22test%22%3A%5B%22collision-lab%22%2C%22xss-fuzz%22%5D%2C%22snapshotName%22%3A%22snapshot-1661601756989%22%2C%22timestamp%22%3A1661618103598%7D&brand=phet&ea&fuzz&stringTest=xss&memoryLimit=1000
Query: brand=phet&ea&fuzz&stringTest=xss&memoryLimit=1000
Uncaught Error: Assertion failed: Corner overlap on left edge
Error: Assertion failed: Corner overlap on left edge
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1661601756989/assert/js/assert.js:28:13)
at assert (Shape.js:2037:14)
at roundedRectangleWithRadii (RectangularButton.ts:204:15)
at createButtonShape (RectangularButton.ts:175:33)
at callback (Multilink.ts:111:10)
at listener (TinyEmitter.ts:95:8)
at emit (ReadOnlyProperty.ts:304:22)
at _notifyListeners (ReadOnlyProperty.ts:255:13)
at unguardedSet (ReadOnlyProperty.ts:239:11)
at set (DerivedProperty.ts:155:12)
id: Bayes Puppeteer
Snapshot from 8/27/2022, 6:02:36 AM
```

Similar to https://github.com/phetsims/build-a-molecule/issues/232

**Comment by samreid** [comment]
Fixed with a workaround like in https://github.com/phetsims/build-a-molecule/issues/232.

**Comment by jonathanolson** [comment]
Doesn't seem to be occurring anymore, thanks!
