### ISSUE TITLE
CT invalid lastTime undefined

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/collision-lab#35]
```
collision-lab : xss-fuzz : load
Query: brand=phet&ea&fuzz&stringTest=xss&memoryLimit=1000
Uncaught Error: Assertion failed: invalid lastTime: undefined
Error: Assertion failed: invalid lastTime: undefined
    at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/snapshot-1570694593619/assert/js/assert.js:22:13)
    at CollisionDetector.detectCollision (https://bayes.colorado.edu/continuous-testing/snapshot-1570694593619/collision-lab/js/common/model/CollisionDetector.js?bust=1570710564452:68:17)
    at PlayArea.step (https://bayes.colorado.edu/continuous-testing/snapshot-1570694593619/collision-lab/js/common/model/PlayArea.js?bust=1570710564452:140:30)
    at IntroModel.stepBackward (https://bayes.colorado.edu/continuous-testing/snapshot-1570694593619/collision-lab/js/common/model/CollisionLabModel.js?bust=1570710564452:75:21)
    at listener (https://bayes.colorado.edu/continuous-testing/snapshot-1570694593619/collision-lab/js/common/view/TimeControlBox.js?bust=1570710564452:41:31)
    at TinyEmitter.emit (https://bayes.colorado.edu/continuous-testing/snapshot-1570694593619/axon/js/TinyEmitter.js?bust=1570710564452:59:55)
    at https://bayes.colorado.edu/continuous-testing/snapshot-1570694593619/axon/js/Emitter.js?bust=1570710564452:35:31
    at Emitter.execute (https://bayes.colorado.edu/continuous-testing/snapshot-1570694593619/axon/js/Action.js?bust=1570710564452:238:20)
    at Emitter.emit (https://bayes.colorado.edu/continuous-testing/snapshot-1570694593619/axon/js/Emitter.js?bust=1570710564452:60:21)
    at PushButtonModel.fire (https://bayes.colorado.edu/continuous-testing/snapshot-1570694593619/sun/js/buttons/PushButtonModel.js?bust=1570710564452:156:25)
id: Bayes Chrome
Approximately 10/10/2019, 2:03:13 AM
collision-lab : xss-fuzz : run
Query: brand=phet&ea&fuzz&stringTest=xss&memoryLimit=1000
Uncaught Error: Assertion failed: invalid lastTime: undefined
Error: Assertion failed: invalid lastTime: undefined
    at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/snapshot-1570694593619/assert/js/assert.js:22:13)
    at CollisionDetector.detectCollision (https://bayes.colorado.edu/continuous-testing/snapshot-1570694593619/collision-lab/js/common/model/CollisionDetector.js?bust=1570710564452:68:17)
    at PlayArea.step (https://bayes.colorado.edu/continuous-testing/snapshot-1570694593619/collision-lab/js/common/model/PlayArea.js?bust=1570710564452:140:30)
    at IntroModel.stepBackward (https://bayes.colorado.edu/continuous-testing/snapshot-1570694593619/collision-lab/js/common/model/CollisionLabModel.js?bust=1570710564452:75:21)
    at listener (https://bayes.colorado.edu/continuous-testing/snapshot-1570694593619/collision-lab/js/common/view/TimeControlBox.js?bust=1570710564452:41:31)
    at TinyEmitter.emit (https://bayes.colorado.edu/continuous-testing/snapshot-1570694593619/axon/js/TinyEmitter.js?bust=1570710564452:59:55)
    at https://bayes.colorado.edu/continuous-testing/snapshot-1570694593619/axon/js/Emitter.js?bust=1570710564452:35:31
    at Emitter.execute (https://bayes.colorado.edu/continuous-testing/snapshot-1570694593619/axon/js/Action.js?bust=1570710564452:238:20)
    at Emitter.emit (https://bayes.colorado.edu/continuous-testing/snapshot-1570694593619/axon/js/Emitter.js?bust=1570710564452:60:21)
    at PushButtonModel.fire (https://bayes.colorado.edu/continuous-testing/snapshot-1570694593619/sun/js/buttons/PushButtonModel.js?bust=1570710564452:156:25)
id: Bayes Chrome
Approximately 10/10/2019, 2:03:13 AM
```

**Comment by veillette** [comment]
The value of lastTime is now initialized from the get-go, therefore there is no possibility of being undefined in the future. Closing
