### ISSUE TITLE
CT - Cannot normalize a zero-magnitude vector

### ISSUE THREAD

**Issue by brandonLi8** [phetsims/collision-lab#51]
<details> <summary>Details</summary>

```
collision-lab : fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1589822633329/collision-lab/collision-lab_en.html?continuousTest=%7B%22test%22%3A%5B%22collision-lab%22%2C%22fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1589822633329%22%2C%22timestamp%22%3A1589825488019%7D&brand=phet&ea&fuzz&memoryLimit=1000
Query: brand=phet&ea&fuzz&memoryLimit=1000
Uncaught Error: Cannot normalize a zero-magnitude vector
Error: Cannot normalize a zero-magnitude vector
at Vector2.normalized (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1589822633329/dot/js/Vector2.js:262:13)
at Line.getStartTangent (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1589822633329/kite/js/segments/Line.js:215:54)
at Line.get startTangent [as startTangent] (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1589822633329/kite/js/segments/Line.js:219:36)
at Line.areStrokedBoundsDilated (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1589822633329/kite/js/segments/Segment.js:106:27)
at Shape.getStrokedBounds (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1589822633329/kite/js/Shape.js:1560:23)
at ArrowNode.computeShapeBounds (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1589822633329/scenery/js/nodes/Path.js:358:34)
at ArrowNode.updateSelfBounds (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1589822633329/scenery/js/nodes/Path.js:285:47)
at ArrowNode.validateSelfBounds (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1589822633329/scenery/js/nodes/Node.js:1153:40)
at ArrowNode.validateBounds (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1589822633329/scenery/js/nodes/Node.js:1177:31)
at BallVelocityVectorNode.validateBounds (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1589822633329/scenery/js/nodes/Node.js:1192:29)
id: Bayes Chrome
Snapshot from 5/18/2020, 11:23:53 AM
```

**Comment by brandonLi8** [comment]
This is a peculiar issue. I can only sometimes replicate it by trying to change the velocity after a inelastic sticky collision with the wall. It also only shows up in CT a small percentage of the time. The stack trace isn't useful.

**Comment by brandonLi8** [comment]
Able to reproduce consistently by:
1. starting the sim
2. setting the collisions to sticky and inelastic (0%)
3. run the sim
4 let the Balls collide into the walls and keep the sim running
5. after a while, this error comes up

**Comment by brandonLi8** [comment]
By process of elimination, the error comes from `BallVectorNode`
```
    // @public
    this.arrowNode = new ArrowNode( 0, 0, viewVector.x, viewVector.y, options );
    this.addChild( this.arrowNode );

    const tipPositionListener = vector => {
      const viewVector = modelViewTransform.modelToViewDelta( vector );
      this.arrowNode.setTip( viewVector.x, viewVector.y );
    };

    tipPositionProperty.link( tipPositionListener );

    const visiblePropertyHandle = visibleProperty.linkAttribute( this, 'visible' );

    // @private {function} disposeBallVectorNode - function to unlink listeners, called in dispose()
    this.disposeBallVectorNode = () => {
      visibleProperty.unlinkAttribute( visiblePropertyHandle );
      tipPositionProperty.unlink( tipPositionListener );
    };
```
When I commented this out, the error didn't come up.

**Comment by brandonLi8** [comment]
Changing the above code to
```
    const tipPositionListener = vector => {
      if ( vector.magnitude > CollisionLabConstants.ZERO_THRESHOLD ) {
        const viewVector = modelViewTransform.modelToViewDelta( vector );
        this.arrowNode.setTip( viewVector.x, viewVector.y );
      }
      else {
        this.arrowNode.setTip( 0, 0 );
      }
    };
```
where i stole
```
  // vector components or magnitudes smaller than this value are treated as effectively zero
  ZERO_THRESHOLD: 1E-10,
```
from vector addition.

This seems to be fixed. I'll keep an eye out for CT before deciding to close.

**Comment by brandonLi8** [comment]
CT has been all green for at least the last 12 snapshots. This seems to be fixed. Closing.
