### ISSUE TITLE
CT alignBounds should be a non-empty finite Bounds2

### ISSUE THREAD

**Issue by brandonLi8** [phetsims/collision-lab#62]
```
collision-lab : fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1590064925545/collision-lab/collision-lab_en.html?continuousTest=%7B%22test%22%3A%5B%22collision-lab%22%2C%22fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1590064925545%22%2C%22timestamp%22%3A1590066890483%7D&brand=phet&ea&fuzz&memoryLimit=1000
Query: brand=phet&ea&fuzz&memoryLimit=1000
Uncaught Error: Assertion failed: alignBounds should be a non-empty finite Bounds2
Error: Assertion failed: alignBounds should be a non-empty finite Bounds2
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1590064925545/assert/js/assert.js:22:13)
at AlignBox.setAlignBounds (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1590064925545/scenery/js/nodes/AlignBox.js:138:15)
at AlignBox.set alignBounds [as alignBounds] (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1590064925545/scenery/js/nodes/AlignBox.js:152:35)
at AlignGroup.setBoxBounds (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1590064925545/scenery/js/nodes/AlignGroup.js:306:26)
at AlignGroup.updateLayout (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1590064925545/scenery/js/nodes/AlignGroup.js:264:14)
at AlignGroup.addAlignBox (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1590064925545/scenery/js/nodes/AlignGroup.js:330:10)
at AlignBox.setGroup (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1590064925545/scenery/js/nodes/AlignBox.js:185:21)
at AlignBox.set group [as group] (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1590064925545/scenery/js/nodes/AlignBox.js:191:29)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1590064925545/scenery/js/nodes/Node.js:5230:23
at arrayEach (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1590064925545/sherpa/lib/lodash-4.17.4.js:537:11)
id: Bayes Chrome
Snapshot from 5/21/2020, 6:42:05 AM
```

**Comment by brandonLi8** [comment]
This looks to be related to #58.

**Comment by brandonLi8** [comment]
Able to reproduce by setting the balls to 0 and re-adding balls back.

**Comment by brandonLi8** [comment]
This is what the `BallValuesPanel` currently looks like this with no balls in the play area
![image](https://user-images.githubusercontent.com/42391580/82587237-0913b280-9b56-11ea-9a75-1701acce934d.png)

**Comment by brandonLi8** [comment]
I fixed this in the commit above by disallowing 0 balls in the play-area. The range of balls is now [1,5].

This is the behavior in the flash sim, but I want to check-in on @arouinfar if this is desired. If we do allow 0 balls this would be a big issue to resolve.

**Comment by brandonLi8** [comment]
This was still showing up on CT, so I went ahead and investigated further. It turns out that I needed to remove `AlignBox` from the `AlignGroup` when their contentNode is disposed.

I tested allowing 0 balls in the play-area and it worked. However, I'm still leaving the range of balls as [1,5] until @arouinfar  comments.

**Comment by arouinfar** [comment]
@brandonLi8 we should never allow 0 balls. A range of [1, 5] is desired.

**Comment by brandonLi8** [comment]
OK, this has been implemented and fixed. Closing.
