### ISSUE TITLE
CT:  value should have typeof number, value=null

### ISSUE THREAD

**Issue by brandonLi8** [phetsims/collision-lab#71]
```
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1590376774622/collision-lab/collision-lab_en.html?continuousTest=%7B%22test%22%3A%5B%22collision-lab%22%2C%22fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1590376774622%22%2C%22timestamp%22%3A1590426040809%7D&brand=phet&ea&fuzz&memoryLimit=1000
Query: brand=phet&ea&fuzz&memoryLimit=1000
Uncaught Error: Assertion failed: value should have typeof number, value=null
Error: Assertion failed: value should have typeof number, value=null
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1590376774622/assert/js/assert.js:22:13)
at Object.isValueValidValueType (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1590376774622/axon/js/ValidatorDef.js:321:39)
at Object.isValueValid (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1590376774622/axon/js/ValidatorDef.js:257:28)
at validate (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1590376774622/axon/js/validate.js:27:18)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1590376774622/axon/js/Property.js:138:27
at TinyEmitter.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1590376774622/axon/js/TinyEmitter.js:69:53)
at NumberProperty._notifyListeners (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1590376774622/axon/js/Property.js:271:25)
at NumberProperty.set (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1590376774622/axon/js/Property.js:171:14)
at NumberProperty.set value [as value] (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1590376774622/axon/js/Property.js:341:32)
at KeypadDialog.submitEdit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1590376774622/collision-lab/js/common/view/KeypadDialog.js:189:32)
id: Bayes Chrome
Snapshot from 5/24/2020, 9:19:34 PM
```

**Comment by brandonLi8** [comment]
I've been running the [snap-shot](https://bayes.colorado.edu/continuous-testing/ct-snapshots/1590376774622/collision-lab/collision-lab_en.html?continuousTest=%7B%22test%22%3A%5B%22collision-lab%22%2C%22fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1590376774622%22%2C%22timestamp%22%3A1590426040809%7D&brand=phet&ea&fuzz&memoryLimit=1000) for at least 30 minutes and no errors have come up.

**Comment by brandonLi8** [comment]
Haven't seen this come up. I'll reopen if it does.

**Comment by brandonLi8** [comment]
This showed up again.

**Comment by brandonLi8** [comment]
Able to reproduce by typing in the negative and hitting submit.

**Comment by brandonLi8** [comment]
Pushed a fix above. Closing.
