### ISSUE TITLE
Assertion failed: invalid elapsedTime: -0.008109736006644663

### ISSUE THREAD

**Issue by brandonLi8** [phetsims/collision-lab#81]
```
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1590696091459/collision-lab/collision-lab_en.html?continuousTest=%7B%22test%22%3A%5B%22collision-lab%22%2C%22fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1590696091459%22%2C%22timestamp%22%3A1590700249472%7D&brand=phet&ea&fuzz&memoryLimit=1000
Query: brand=phet&ea&fuzz&memoryLimit=1000
Uncaught Error: Assertion failed: invalid elapsedTime: -0.008109736006644663
Error: Assertion failed: invalid elapsedTime: -0.008109736006644663
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1590696091459/assert/js/assert.js:22:13)
at Path.updatePath (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1590696091459/collision-lab/js/common/model/Path.js:97:15)
at CollisionDetector.collideBalls (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1590696091459/collision-lab/js/common/model/CollisionDetector.js:167:18)
at CollisionDetector.handleAllBallToBallCollisions (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1590696091459/collision-lab/js/common/model/CollisionDetector.js:100:16)
at CollisionDetector.step (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1590696091459/collision-lab/js/common/model/CollisionDetector.js:64:10)
at Explore2DModel.stepManual (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1590696091459/collision-lab/js/common/model/CollisionLabModel.js:192:28)
at Explore2DModel.stepForward (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1590696091459/collision-lab/js/common/model/CollisionLabModel.js:217:24)
at listener (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1590696091459/collision-lab/js/common/view/CollisionLabTimeControlNode.js:54:27)
at TinyEmitter.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1590696091459/axon/js/TinyEmitter.js:69:53)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1590696091459/axon/js/Emitter.js:33:29
id: Bayes Chrome
Snapshot from 5/28/2020, 2:01:31 PM
```

**Comment by brandonLi8** [comment]
This seems to happen when the step forward button is pressed.

**Comment by brandonLi8** [comment]
For some reason, when I a stepped the sim forward, this error came up. But now, I can't seem to reproduce.

**Comment by brandonLi8** [comment]
I figured it out. When the balls are placed on top of each other, the physics engine tries to reconstruct it, but since the time is just starting, it ends up being a negative value. fixing.

**Comment by brandonLi8** [comment]
fixed in the commit above. Will reopen if it pops up again.
