### ISSUE TITLE
CT invalid collisionContactTime

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/collision-lab#92]
```
collision-lab : fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1591855018421/collision-lab/collision-lab_en.html?continuousTest=%7B%22test%22%3A%5B%22collision-lab%22%2C%22fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1591855018421%22%2C%22timestamp%22%3A1591868228326%7D&brand=phet&ea&fuzz&memoryLimit=1000
Query: brand=phet&ea&fuzz&memoryLimit=1000
Uncaught Error: Assertion failed: invalid collisionContactTime: -0.03169023316518427
Error: Assertion failed: invalid collisionContactTime: -0.03169023316518427
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1591855018421/assert/js/assert.js:22:13)
at IntroBallSystem.registerChangeInMomentumCollision (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1591855018421/collision-lab/js/intro/model/IntroBallSystem.js:218:15)
at IntroCollisionEngine.registerExactBallToBallCollision (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1591855018421/collision-lab/js/intro/model/IntroCollisionEngine.js:54:23)
at IntroCollisionEngine.collideBalls (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1591855018421/collision-lab/js/common/model/CollisionEngine.js:217:10)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1591855018421/collision-lab/js/common/model/CollisionEngine.js:145:14
at Object.forEachPossiblePair (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1591855018421/collision-lab/js/common/CollisionLabUtils.js:59:9)
at IntroCollisionEngine.handleBallToBallCollisions (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1591855018421/collision-lab/js/common/model/CollisionEngine.js:140:23)
at IntroCollisionEngine.step (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1591855018421/collision-lab/js/common/model/CollisionEngine.js:79:10)
at IntroModel.stepManual (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1591855018421/collision-lab/js/common/model/CollisionLabModel.js:178:26)
at IntroModel.step (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1591855018421/collision-lab/js/common/model/CollisionLabModel.js:159:42)
id: Bayes Chrome
Snapshot from 6/10/2020, 11:56:58 PM

----------------------------------

collision-lab : xss-fuzz
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1591855018421/collision-lab/collision-lab_en.html?continuousTest=%7B%22test%22%3A%5B%22collision-lab%22%2C%22xss-fuzz%22%5D%2C%22snapshotName%22%3A%22snapshot-1591855018421%22%2C%22timestamp%22%3A1591858440711%7D&brand=phet&ea&fuzz&stringTest=xss&memoryLimit=1000
Query: brand=phet&ea&fuzz&stringTest=xss&memoryLimit=1000
Uncaught Error: Assertion failed: invalid collisionContactTime: -0.07785071569095625
Error: Assertion failed: invalid collisionContactTime: -0.07785071569095625
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1591855018421/assert/js/assert.js:22:13)
at IntroBallSystem.registerChangeInMomentumCollision (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1591855018421/collision-lab/js/intro/model/IntroBallSystem.js:218:15)
at IntroCollisionEngine.registerExactBallToBallCollision (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1591855018421/collision-lab/js/intro/model/IntroCollisionEngine.js:54:23)
at IntroCollisionEngine.collideBalls (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1591855018421/collision-lab/js/common/model/CollisionEngine.js:217:10)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1591855018421/collision-lab/js/common/model/CollisionEngine.js:145:14
at Object.forEachPossiblePair (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1591855018421/collision-lab/js/common/CollisionLabUtils.js:59:9)
at IntroCollisionEngine.handleBallToBallCollisions (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1591855018421/collision-lab/js/common/model/CollisionEngine.js:140:23)
at IntroCollisionEngine.step (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1591855018421/collision-lab/js/common/model/CollisionEngine.js:79:10)
at IntroModel.stepManual (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1591855018421/collision-lab/js/common/model/CollisionLabModel.js:178:26)
at IntroModel.step (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1591855018421/collision-lab/js/common/model/CollisionLabModel.js:159:42)
id: Bayes Chrome
Snapshot from 6/10/2020, 11:56:58 PM

----------------------------------

collision-lab : xss-fuzz
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1591855018421/collision-lab/collision-lab_en.html?continuousTest=%7B%22test%22%3A%5B%22collision-lab%22%2C%22xss-fuzz%22%5D%2C%22snapshotName%22%3A%22snapshot-1591855018421%22%2C%22timestamp%22%3A1591871791795%7D&brand=phet&ea&fuzz&stringTest=xss&memoryLimit=1000
Query: brand=phet&ea&fuzz&stringTest=xss&memoryLimit=1000
Uncaught Error: Assertion failed: invalid collisionContactTime: -0.1518199999999999
Error: Assertion failed: invalid collisionContactTime: -0.1518199999999999
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1591855018421/assert/js/assert.js:22:13)
at IntroBallSystem.registerChangeInMomentumCollision (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1591855018421/collision-lab/js/intro/model/IntroBallSystem.js:218:15)
at IntroCollisionEngine.registerExactBallToBallCollision (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1591855018421/collision-lab/js/intro/model/IntroCollisionEngine.js:54:23)
at IntroCollisionEngine.collideBalls (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1591855018421/collision-lab/js/common/model/CollisionEngine.js:217:10)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1591855018421/collision-lab/js/common/model/CollisionEngine.js:145:14
at Object.forEachPossiblePair (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1591855018421/collision-lab/js/common/CollisionLabUtils.js:59:9)
at IntroCollisionEngine.handleBallToBallCollisions (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1591855018421/collision-lab/js/common/model/CollisionEngine.js:140:23)
at IntroCollisionEngine.step (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1591855018421/collision-lab/js/common/model/CollisionEngine.js:79:10)
at IntroModel.stepManual (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1591855018421/collision-lab/js/common/model/CollisionLabModel.js:178:26)
at IntroModel.step (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1591855018421/collision-lab/js/common/model/CollisionLabModel.js:159:42)
id: Bayes Chrome
Snapshot from 6/10/2020, 11:56:58 PM
```

**Comment by brandonLi8** [comment]
Thanks @KatieWoe.

**Comment by brandonLi8** [comment]
Should be fixed in the commit above. Will keep an eye out on CT.

**Comment by brandonLi8** [comment]
Looks to be fixed. Closing.
