### ISSUE TITLE
CT Missing string information for collision-lab kg and invalid unitsString: undefined

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/collision-lab#94]
```
collision-lab : build
Build failed with status code 1:
Running "report-media" task

Running "clean" task

Running "build" task
Building runnable repository (collision-lab, brands: phet)
Building brand: phet
>> Webpack build complete: 3653ms
Fatal error: Perennial task failed:
AssertionError [ERR_ASSERTION]: Missing string information for collision-lab kg
at locales.forEach.locale (/data/share/phet/continuous-testing/ct-snapshots/1591955849069/chipper/js/grunt/getStringMap.js:213:9)
at Array.forEach (<anonymous>:null:null)
at partialStringKeys.forEach.partialStringKey (/data/share/phet/continuous-testing/ct-snapshots/1591955849069/chipper/js/grunt/getStringMap.js:202:15)
at Array.forEach (<anonymous>:null:null)
at reposWithUsedStrings.forEach.repo (/data/share/phet/continuous-testing/ct-snapshots/1591955849069/chipper/js/grunt/getStringMap.js:201:23)
at Array.forEach (<anonymous>:null:null)
at module.exports (/data/share/phet/continuous-testing/ct-snapshots/1591955849069/chipper/js/grunt/getStringMap.js:153:24)
at module.exports (/data/share/phet/continuous-testing/ct-snapshots/1591955849069/chipper/js/grunt/buildRunnable.js:126:21)

Full Error details:
{
"generatedMessage": false,
"name": "AssertionError [ERR_ASSERTION]",
"code": "ERR_ASSERTION",
"actual": false,
"expected": true,
"operator": "=="
}
Snapshot from 6/12/2020, 3:57:29 AM

----------------------------------

collision-lab : fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1591955849069/collision-lab/collision-lab_en.html?continuousTest=%7B%22test%22%3A%5B%22collision-lab%22%2C%22fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1591955849069%22%2C%22timestamp%22%3A1591958954316%7D&brand=phet&ea&fuzz&memoryLimit=1000
Query: brand=phet&ea&fuzz&memoryLimit=1000
Uncaught Error: Assertion failed: invalid unitsString: undefined
Error: Assertion failed: invalid unitsString: undefined
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1591955849069/assert/js/assert.js:22:13)
at KeypadDialog.beginEdit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1591955849069/collision-lab/js/common/view/KeypadDialog.js:150:15)
at fire (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1591955849069/collision-lab/js/common/view/BallValuesPanelNumberDisplay.js:130:24)
at TinyEmitter.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1591955849069/axon/js/TinyEmitter.js:69:53)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1591955849069/axon/js/Emitter.js:33:29
at Emitter.execute (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1591955849069/axon/js/Action.js:225:18)
at Emitter.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1591955849069/axon/js/Emitter.js:58:19)
at FireListener.fire (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1591955849069/scenery/js/listeners/FireListener.js:95:23)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1591955849069/scenery/js/listeners/FireListener.js:118:14
at FireListener.onPress (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1591955849069/scenery/js/listeners/PressListener.js:590:17)
id: Bayes Chrome
Snapshot from 6/12/2020, 3:57:29 AM

----------------------------------

collision-lab : fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1591955849069/collision-lab/collision-lab_en.html?continuousTest=%7B%22test%22%3A%5B%22collision-lab%22%2C%22fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1591955849069%22%2C%22timestamp%22%3A1591965162087%7D&brand=phet&ea&fuzz&memoryLimit=1000
Query: brand=phet&ea&fuzz&memoryLimit=1000
Uncaught Error: Assertion failed: invalid unitsString: undefined
Error: Assertion failed: invalid unitsString: undefined
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1591955849069/assert/js/assert.js:22:13)
at KeypadDialog.beginEdit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1591955849069/collision-lab/js/common/view/KeypadDialog.js:150:15)
at fire (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1591955849069/collision-lab/js/common/view/BallValuesPanelNumberDisplay.js:130:24)
at TinyEmitter.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1591955849069/axon/js/TinyEmitter.js:69:53)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1591955849069/axon/js/Emitter.js:33:29
at Emitter.execute (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1591955849069/axon/js/Action.js:225:18)
at Emitter.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1591955849069/axon/js/Emitter.js:58:19)
at FireListener.fire (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1591955849069/scenery/js/listeners/FireListener.js:95:23)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1591955849069/scenery/js/listeners/FireListener.js:118:14
at FireListener.onPress (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1591955849069/scenery/js/listeners/PressListener.js:590:17)
id: Bayes Chrome
Snapshot from 6/12/2020, 3:57:29 AM

----------------------------------

collision-lab : xss-fuzz
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1591955849069/collision-lab/collision-lab_en.html?continuousTest=%7B%22test%22%3A%5B%22collision-lab%22%2C%22xss-fuzz%22%5D%2C%22snapshotName%22%3A%22snapshot-1591955849069%22%2C%22timestamp%22%3A1591959117815%7D&brand=phet&ea&fuzz&stringTest=xss&memoryLimit=1000
Query: brand=phet&ea&fuzz&stringTest=xss&memoryLimit=1000
Uncaught Error: Assertion failed: invalid unitsString: undefined
Error: Assertion failed: invalid unitsString: undefined
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1591955849069/assert/js/assert.js:22:13)
at KeypadDialog.beginEdit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1591955849069/collision-lab/js/common/view/KeypadDialog.js:150:15)
at fire (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1591955849069/collision-lab/js/common/view/BallValuesPanelNumberDisplay.js:130:24)
at TinyEmitter.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1591955849069/axon/js/TinyEmitter.js:69:53)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1591955849069/axon/js/Emitter.js:33:29
at Emitter.execute (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1591955849069/axon/js/Action.js:225:18)
at Emitter.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1591955849069/axon/js/Emitter.js:58:19)
at FireListener.fire (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1591955849069/scenery/js/listeners/FireListener.js:95:23)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1591955849069/scenery/js/listeners/FireListener.js:118:14
at FireListener.onPress (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1591955849069/scenery/js/listeners/PressListener.js:590:17)
id: Bayes Chrome
Snapshot from 6/12/2020, 3:57:29 AM

----------------------------------

collision-lab : xss-fuzz
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1591955849069/collision-lab/collision-lab_en.html?continuousTest=%7B%22test%22%3A%5B%22collision-lab%22%2C%22xss-fuzz%22%5D%2C%22snapshotName%22%3A%22snapshot-1591955849069%22%2C%22timestamp%22%3A1591967746547%7D&brand=phet&ea&fuzz&stringTest=xss&memoryLimit=1000
Query: brand=phet&ea&fuzz&stringTest=xss&memoryLimit=1000
Uncaught Error: Assertion failed: invalid unitsString: undefined
Error: Assertion failed: invalid unitsString: undefined
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1591955849069/assert/js/assert.js:22:13)
at KeypadDialog.beginEdit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1591955849069/collision-lab/js/common/view/KeypadDialog.js:150:15)
at fire (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1591955849069/collision-lab/js/common/view/BallValuesPanelNumberDisplay.js:130:24)
at TinyEmitter.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1591955849069/axon/js/TinyEmitter.js:69:53)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1591955849069/axon/js/Emitter.js:33:29
at Emitter.execute (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1591955849069/axon/js/Action.js:225:18)
at Emitter.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1591955849069/axon/js/Emitter.js:58:19)
at FireListener.fire (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1591955849069/scenery/js/listeners/FireListener.js:95:23)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1591955849069/scenery/js/listeners/FireListener.js:118:14
at FireListener.onPress (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1591955849069/scenery/js/listeners/PressListener.js:590:17)
id: Bayes Chrome
Snapshot from 6/12/2020, 3:57:29 AM
```

**Comment by brandonLi8** [comment]
Should be fixed in the commit above. Ill keep an eye out.

**Comment by brandonLi8** [comment]
Looks fixed. Closing.
